description = "Pike & West is Germantown's premier art gallery and event venue. Host your wedding, corporate event, birthday, or private party in our elegant space."
author = "Pike & West"

# Default Open Graph image (used when pages don't specify their own)
defaultOgImage = "/images/photos/og-default.jpg"

[contact]
  phone = "901.206.5575"
  email = "events@pikeandwest.com"
  address = "2277 West Street"
  city = "Germantown"
  state = "TN"
  zip = "38138"
  hours = "Available by appointment only.<br>Call or email to reserve a tour."
  googleMapsUrl = "https://maps.app.goo.gl/7fNG7K7BEPQKpNzs8"

[social]
  instagram = "https://www.instagram.com/pikeandwest/"
  facebook = "https://www.facebook.com/pikeandwest"
  twitter = "pikeandwest"

[analytics]
  googleTagManager = "GTM-P8XR8C5S"

[maps]
  embed = "https://maps.google.com/maps?q=Pike+and+West,+2277+West+Street,+Germantown,+TN+38138&t=&z=15&ie=UTF8&iwloc=&output=embed"

[forms]
  contactEmbed = "https://portal.pikeandwest.com/public/inquiry"
  # HoneyBook widget placement ID (loaded via JavaScript, not iframe)
  galleryApplicationPlacementId = "65174362ef543a000898bc37"

[ticketTailor]
  # Ticket Tailor widget URL - custom domain: tix.pikeandwest.com
  widgetUrl = "https://tix.pikeandwest.com/all-tickets/pw/"
  fallbackUrl = "https://tix.pikeandwest.com/all-tickets/pw/?ref=website_widget"
