description = "Pike & West is Germantown's premier art gallery and event venue. Host your wedding, corporate event, birthday, or private party in our elegant space."
author = "Pike & West"

[contact]
  phone = "901.206.5575"
  email = "events@pikeandwest.com"
  address = "2277 West Street"
  city = "Germantown"
  state = "TN"
  zip = "38138"
  hours = "Available by appointment only.<br>Call or email to reserve a tour."
  googleMapsUrl = "https://maps.app.goo.gl/7fNG7K7BEPQKpNzs8"

[social]
  instagram = "https://www.instagram.com/pikeandwest/"
  facebook = "https://www.facebook.com/pikeandwest"

[analytics]
  googleTagManager = "GTM-P8XR8C5S"

[maps]
  embed = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3262.8!2d-89.8!3d35.08!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzXCsDA0JzQ4LjAiTiA4OcKwNDgnMDAuMCJX!5e0!3m2!1sen!2sus!4v1"

[forms]
  contactEmbed = "https://portal.pikeandwest.com/public/inquiry"
  # HoneyBook widget placement ID (loaded via JavaScript, not iframe)
  galleryApplicationPlacementId = "65174362ef543a000898bc37"
